version: '3.3'
services:
  geth:
    build: .
    container_name: ethereum
    restart: always
    networks:
      ctfnet:
        ipv4_address: 172.6.0.100

  proxy:
    image: nginx:1.20-alpine
    container_name: rpcproxy
    ports:
      - '40002:8545'
    links:
      - geth
    volumes:
      - ./njs:/etc/nginx/njs
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - geth
    restart: always
    networks:
      - ctfnet

  faucet:
    image: chainflag/eth-faucet:1.0.0
    container_name: ethfaucet
    environment:
      - WEB3_PROVIDER=http://geth:8545
      - KEYSTORE=/app/keystore
    ports:
      - '40001:8080'
    links:
      - geth
    volumes:
      - ./config/keystore:/app/keystore
      - ./config/password.txt:/app/password.txt
    entrypoint: './eth-faucet -payout 100 -chainname "SEETF" -interval 10'
    depends_on:
      - geth
    restart: always
    networks:
      - ctfnet

networks:
  ctfnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.6.0.0/24
